man(anatoliy).
man(dimitriy).
man(jack).
man(petya).
woman(zoya).
woman(anna).
woman(alisa).
woman(aleksa).
woman(sveta).
dite(dimitriy,anatoliy).
dite(dimitriy,zoya).
dite(anna,anatoliy).
dite(anna,zoya).
dite(kolya,dimitriy).
dite(kolya,sveta).
dite(petya,sveta).
dite(alisa,anna).
dite(alisa,jack).
dite(alexa,anna).
dite(alexa,jack).
sin(X,Y):-dite(X,Y),man(X).
doch(X,Y):-dite(X,Y),woman(X).
brak(X,Y):-dite(Z,X),dite(Z,Y).
brak(X,Y):-dite(Z,X),!,dite(Z,Y),not(X=Y).
bro(X,Y):-man(Y),!,dite(Y,BRAT),dite(X,BRAT).
